{% set name = "pathlib-abc" %}
{% set version = "0.4.0" %}
{% set pypi_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 188a25cb55ffabf7472c7c50b71574a49385c9e06a660862f7f043f9dcfd214b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pathlib_abc

about:
  home: https://github.com/barneygale/pathlib-abc
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Base classes for pathlib.Path-ish objects
  dev_url: https://github.com/barneygale/pathlib-abc

extra:
  recipe-maintainers:
    - kfot
