{% set name = "pathlib-abc" %}
{% set version = "0.3.1" %}
{% set pypi_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 811395d2793a1c675ff79c3246d3d6b41a0f96a3a1479c2e96c56b0a51402227

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pathlib_abc

about:
  home: https://github.com/barneygale/pathlib-abc
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Base classes for pathlib.Path-ish objects
  dev_url: https://github.com/barneygale/pathlib-abc

extra:
  recipe-maintainers:
    - kfot
